---
title: "00_preparation"
output: html_document
---
Importing the libraries
```{r}
library(dplyr)
library(janitor)
library(tibble)
```

Loading the two datasets
```{r}
otu_raw <- read.delim(file.path(data_dir, "otu_table.xls"),
                      sep = "\t", header = TRUE, check.names = FALSE)

metadata <- read.delim(file.path(data_dir, "sample_data.xls"),
                       sep = "\t", header = TRUE, check.names = FALSE)
```

Renaming the metadata column for easier handling and trimming
```{r}
colnames(metadata)[colnames(metadata) == "#SampleID"] <- "sample_id"

metadata$sample_id <- trimws(metadata$sample_id)
```

Filtering the otu data and joining with the metadata
```{r}
otu <- otu_raw %>%
  tibble::column_to_rownames("featureid") %>%
  t() %>%
  as.data.frame()

otu$sample_id <- rownames(otu)

dat <- dplyr::inner_join(metadata, otu, by = "sample_id")

# Remove Denmark samples
dat <- dat %>%
  filter(Country != "Denmark")
```

Creating a dx column with the health status column and removing the unnecessary metadata
```{r}
dat$dx <- factor(dat$Disease.MESH.ID)
dat$dx <- factor(dat$dx, levels = c("D003093", "D006262"))

dat$Country <- as.factor(dat$Country)
dat$Country <- as.numeric(dat$Country)

dat <- dat %>%
  dplyr::select(-sample_id, -Disease.MESH.ID, -Disease.name)

table(dat$dx)
```

Saving the prepared data to the data folder
```{r}
saveRDS(dat, file.path(data_dir, "prepared_data_ndkwc.rds"))
```

