---
title: "Testrun"
output: html_document
---
<<<<<<< HEAD

```{r}
library(phyloseq)
library(tidyverse)
library(ape)
```


```{r}
# otu_table.tsv
# - first column: MAG IDs
# - remaining columns: samples
# - values: abundance values for each MAG in each sample

otu_df <- read.delim(
  file.path("data/D003093_Colitis,_Ulcerative/species", "otu_table.xls"),
  check.names = FALSE
)


# tax_table.tsv
# - first column: MAG IDs
# - remaining columns: taxonomy ranks

tax_df <- read.delim(
  file.path("data/D003093_Colitis,_Ulcerative/species", "tax_table.xls"),
  check.names = FALSE
)


# sample_data.tsv
# - first column: sample IDs
# - remaining columns: metadata variables

sample_df <- read.delim(
  file.path("data/D003093_Colitis,_Ulcerative/species", "sample_data.xls"),
  check.names = FALSE
)
```


```{r}
tree <- ape::read.tree(file.path("data/D003093_Colitis,_Ulcerative/species", "tree.nwk"))
```


```{r}
otu_mat <- otu_df %>%
  column_to_rownames("featureid") %>%
  as.matrix()

tax_mat <- tax_df %>%
  column_to_rownames("#featureid") %>%
  as.matrix()

sample_tab <- sample_df %>%
  column_to_rownames("#SampleID")
```


```{r}
ps <- phyloseq(
  otu_table(otu_mat, taxa_are_rows = TRUE),
  tax_table(tax_mat),
  sample_data(sample_tab),
  phy_tree(tree)
)

# Inspect the phyloseq object
ps
sample_variables(ps)
rank_names(ps)
sample_names(ps)
taxa_names(ps)
sample_sums(ps)
nsamples(ps)
ntaxa(ps)
phy_tree(ps)
```


```{r}
shannon <- estimate_richness(
  ps,
  measures = c("Shannon")
)

head(shannon)

# Group samples by body site
plot_richness(
  ps,
  measures = c("Shannon"),
  color = "Country"
)
```

=======
>>>>>>> 9b05ece507410af7d30b8a78cc1731aad6871565
